# Generated by Django 5.1.6 on 2025-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
