# Generated by Django 5.1.6 on 2025-05-12 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_follpwermodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollpwerModel',
            new_name='FollowerModel',
        ),
    ]
