name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: cp .env_example .env

    - name: Build and start containers
      run: docker compose up --build -d

    - name: Wait for services to be ready
      run: sleep 10

    - name: Run tests
      run: docker compose exec backend pytest
